server:
  port: 8084
spring:
  application:
    name: goods-web
  thymeleaf:
    cache: false
  rabbitmq:
    host: server
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      exchange: leyou.item.exchange # 配置默认交换机 不配置走rabbit的默认交换机
    publisher-confirms: true # 生产者确认机制，确保消息会正确发送，如果发送失败会有错误回执，从而触发重试

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5 # 心跳时间
    lease-expiration-duration-in-seconds: 15 # 过期时间
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5 # 拉取服务时间