server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    username: root
    password: root
    url: "jdbc:mysql:///leyou"
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: server
  rabbitmq:
    host: server
    username: leyou
    password: leyou
    virtual-host: /leyou

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:10086/eureka"
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.leyou.pojo.user


